#### STUDENT SIGN UP
POST http://localhost:3000/api/auth/signUp/student
Content-Type: application/json

{
  "name": "Victor Pinto",
  "email": "vkpinto1234@gmail.com",
  "password": "SuperStrongPassword123"
}


###  VERIFY OTP (after sign-up)
POST http://localhost:3000/api/auth/verify-otp/student
Content-Type: application/json

{
  "otp": "021181",
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVmljdG9yIFBpbnRvIiwiZW1haWwiOiJ2a3BpbnRvMTIzNEBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCQ2QjV2bFd0ZzNFNlJKdFNRQVJ3SjMuMll4MHFBemVPRW9EQVlOMU9RQm52WHRpaGhib2dRVyIsImVudE5hbWUiOiJ2aWN0b3IgZW50ZXJwcmlzZSIsInBob25lIjoiMTIzNDU2Nzg5MCIsImxvY2F0aW9uIjoiRW50ZXJwcmlzZSBMb2NhdGlvbiIsImRlc2NyaXB0aW9uIjoiRW50ZXJwcmlzZSBEZXNjcmlwdGlvbiIsIm90cCI6IjAyMTE4MSIsImlhdCI6MTc2MTgzMDQ5MiwiZXhwIjoxNzYxODMwNzkyfQ.RwjJO9arvDQ8ZbLkqyCgBSoO9mxaXzmFr8lLy9DYw_o"
}


### vendor sign up
POST http://localhost:3000/api/auth/signUp/vendor
Content-Type: application/json

{
  "name": "Victor Pinto",
  "email": "vkpinto1234@gmail.com",
  "password": "1234567890",
  "entName": "victor enterprise",
  "phone": "1234567890",
  "location": "Enterprise Location",
  "description": "Enterprise Description"
  
}

### verify otp  vendor 
POST http://localhost:3000/api/auth/verify-otp/vendor
Content-Type: application/json

{
  "otp": "741485", 
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVmljdG9yIFBpbnRvIiwiZW1haWwiOiJ2a3BpbnRvMTIzNEBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRNbExxQkNWVU5weUdITXYuSENnRTIuWDZPSS5hMGI5N0NRamN3SnJ0QkgueDQxQ1JhdXFyRyIsImVudE5hbWUiOiJ2aWN0b3IgZW50ZXJwcmlzZSIsInBob25lIjoiMTIzNDU2Nzg5MCIsImxvY2F0aW9uIjoiRW50ZXJwcmlzZSBMb2NhdGlvbiIsImRlc2NyaXB0aW9uIjoiRW50ZXJwcmlzZSBEZXNjcmlwdGlvbiIsIm90cCI6Ijc0MTQ4NSIsImlhdCI6MTc2MTgzMDkyNCwiZXhwIjoxNzYxODMxMjI0fQ.MsnqkaKeWPUwXMM5Ka0agAzMmd6Q-j9CzLV9o2kf6wM"
}

### LOGIN (student or vendor)
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "",
  "password": ""
}  


### ENABLE 2FA

POST http://localhost:3000/api/auth/2fa/enable
Authorization: Bearer 
Content-Type: application/json


### DISABLE 2FA

POST http://localhost:3000/api/auth/2fa/disable
Authorization: Bearer 
Content-Type: application/json





### VERIFY LOGIN OTP (only when 2FA is enabled)
POST http://localhost:3000/api/auth/verify-2fa
Content-Type: application/json

{
  "otp": "123456",
  "token": ""
}


### RESEND OTP 
POST http://localhost:3000/api/auth/resend-otp
content-type: application/json

{
  "email": ""
}

### reset password 
POST http://localhost:3000/api/auth/reset-password
Content-Type: application/json

{
  "email": "",
  "newPassword": ""
}
