####  SIGN UP
POST http://localhost:3000/api/auth/signUp/student
Content-Type: application/json

{
  "name": "Victor Pinto",
  "email": "vkpinto1234@gmail.com",
  "password": "SuperStrongPassword123"
}


###  VERIFY OTP (after sign-up)
POST http://localhost:3000/api/auth/verify-otp
Content-Type: application/json

{
  "otp": "962657",
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVmljdG9yIFBpbnRvIiwiZW1haWwiOiJ2a3BpbnRvMTIzNEBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRsbEFIdm4ycWp0QndmNFV3ZXk0NG0uZTRobWxyVFlZOVd6Mkxzb1JhZDYuWGxZMzlkbnBHMiIsIm90cCI6Ijk2MjY1NyIsImlhdCI6MTc2MTE0NjMzMiwiZXhwIjoxNzYxMTQ2NjMyfQ.rP11Li4VU0WqrgvGvoWNfd99FRfjWNOL1G8RcR-KnrI"
}


###  LOGIN (2FA off)
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "victor@example.com",
  "password": "SuperStrongPassword123"
}


### ENABLE 2FA
# Copy token from login response
POST http://localhost:3000/api/auth/2fa/enable
Authorization: Bearer 
Content-Type: application/json


### DISABLE 2FA
# Copy token from login response
POST http://localhost:3000/api/auth/2fa/disable
Authorization: Bearer 
Content-Type: application/json


### LOGIN (2FA ON)
# If 2FA is enabled, this will trigger OTP email before login completes.
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "victor@example.com",
  "password": "SuperStrongPassword123"
}


### VERIFY LOGIN OTP (only when 2FA is enabled)
# Use token returned from 2FA loginh
POST http://localhost:3000/api/auth/verify-login-otp
Content-Type: application/json

{
  "otp": "123456",
  "token": ""
}


### TEST AUTH-PROTECTED ROUTE
# Replace {{auth_token}} with the token from successful login or verified OTP login
GET http://localhost:3000/api/protected
Authorization: Bearer 
